function changecolor(){
    var r = Math.floor(Math.random() * 256);
    var g = Math.floor(Math.random() * 256);
    var b = Math.floor(Math.random() * 256);
    var mycolor1 ="rgb("+r+","+g+","+b+")";
    
   
    
    
    document.getElementById("id1").style.background=mycolor1;
    document.getElementById("id2").style.background=mycolor1;
    document.getElementById("id3").style.background=mycolor1;
    document.getElementById("id4").style.background=mycolor1;
    document.getElementById("id5").style.background=mycolor1;
    document.getElementById("id6").style.background=mycolor1;
    document.getElementById("id7").style.background=mycolor1;
    document.getElementById("id8").style.background=mycolor1;
    document.getElementById("id9").style.background=mycolor1;
    document.getElementById("id10").style.background=mycolor1;
    document.getElementById("id11").style.background=mycolor1;
    document.getElementById("id12").style.background=mycolor1;
    document.getElementById("id13").style.background=mycolor1;
    document.getElementById("id14").style.background=mycolor1;
    document.getElementById("id15").style.background=mycolor1;
    document.getElementById("id16").style.background=mycolor1;
    document.getElementById("id17").style.background=mycolor1;
    document.getElementById("id18").style.background=mycolor1;
    document.getElementById("id19").style.background=mycolor1;
    document.getElementById("id20").style.background=mycolor1;
    document.getElementById("id21").style.background=mycolor1;
   
 }

 var c3note = new Audio()
 c3note.src = "tones/c3note.mp3";
 var d3note = new Audio()
 d3note.src = "tones/d3note.mp3";
 var e3note = new Audio()
 e3note.src = "tones/e3note.mp3";
 var f3note = new Audio()
 f3note.src = "tones/f3note.mp3";
 var g3note = new Audio()
 g3note.src = "tones/g3note.mp3";
 var a3note = new Audio()
 a3note.src = "tones/a3note.mp3";
 var b3note = new Audio()
 b3note.src = "tones/b3note.mp3";
 var c4note = new Audio()
 c4note.src = "tones/c4note.mp3";
 var d4note = new Audio()
 d4note.src = "tones/d4note.mp3";
 var e4note = new Audio()
 e4note.src = "tones/e4note.mp3";
 var f4note = new Audio()
 f4note.src = "tones/f4note.mp3";
 var g4note = new Audio()
 g4note.src = "tones/g4note.mp3";
 var a4note = new Audio()
 a4note.src = "tones/a4note1.wav";
 var b4note = new Audio()
 b4note.src = "tones/b4note.mp3";
 var c5note = new Audio()
 c5note.src = "tones/c5note.mp3";
 var d5note = new Audio()
 d5note.src = "tones/d5note.mp3";
 var e5note = new Audio()
 e5note.src = "tones/e5note.mp3";
 var f5note = new Audio()
 f5note.src = "tones/f5note.mp3";
 var g5note = new Audio()
 g5note.src = "tones/g5note.mp3";
 var a5note = new Audio()
 a5note.src = "tones/a5note.mp3";
 var b5note = new Audio()
 b5note.src = "tones/b5note.mp3";
 var CS3note = new Audio()
 CS3note.src = "tones/CS3note.mp3";
 var DS3note = new Audio()
 DS3note.src = "tones/DS3note.mp3";
 var FS3note = new Audio()
 FS3note.src = "tones/FS3note.mp3";
 var GS3note = new Audio()
 GS3note.src = "tones/GS3note.mp3";
 var AS3note = new Audio()
 AS3note.src = "tones/AS3note.mp3";
 var CS4note = new Audio()
 CS4note.src = "tones/CS4note.mp3";
 var DS4note = new Audio()
 DS4note.src = "tones/DS4note.mp3";
 var FS4note = new Audio()
 FS4note.src = "tones/FS4note.mp3";
 var GS4note = new Audio()
 GS4note.src = "tones/GS4note.mp3";
 var AS4note = new Audio()
 AS4note.src = "tones/AS4note.mp3";
 var CS5note = new Audio()
 CS5note.src = "tones/CS5note.mp3";
 var DS5note = new Audio()
 DS5note.src = "tones/DS5note.mp3";
 var FS5note = new Audio()
 FS5note.src = "tones/FS5note.mp3";
 var GS5note = new Audio()
 GS5note.src = "tones/GS5note.mp3";
 var AS5note = new Audio()
 AS5note.src = "tones/AS5note.mp3";